language: groovy

jdk:
  - openjdk8
  - openjdk11
  - openjdk12
  - openjdk13

git:
  depth: false

addons:
  apt:
    packages:
      - shellcheck
      - graphviz

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

install: skip

script:
  - ./.ci.sh
  - find . -type f -exec grep -l '^#!/bin/bash' {} + | xargs shellcheck

env:
  global:
    # use `travis env set GH_TOKEN XXX` to set token to publish contents to GitHub pages
    secure: "NaeNW1opfKrxPPRvS/IH3besoQt1nITXC4Jo+mTI/oKZbxfbeH9E2uSQ65KJhJsP5UvvYgRdK7SwW0znX8fijmwSnsru5gWXPRehFrk/O5xhzutvnCl7jmuLWwg5Ed4FfGi63Wg/DHQgXS8e7w7W/UNHPH3cW94dIHMpYbr+wMmFfumGVgHk1gjFpryXd1zaa2/YTIPD9DMZa41pObd+aSFMl/uvt8DRZg3P3dkCgTJqwFebW/5cl6+/8rRsy+WmHR0Sv7+aag32XxP9Crl1rCFypaxbyexcLuE/iBrlJIvYAFUiJ0JL+Lqaii8Kfs3DmY5cw4yuMu72PwULkfwfF/MZ0T6TYNnpOo1U3htaqGDmsLi/h/21wILxh2kQ2VuHgbh1r542E/bQr/IBPWcJeZHREl4nbft0EuTSz78shsx3Q3+VdPj0VCNwoyJHRiSFdImdd+qsmP1EjxbJtDGzvta7suFq4Jm+/YRqCRZKOxQMaaqNuK79nk+09MK0ZbyNS7kVLmx6LfQPfi8A/uAmGvkdInULDOdYZxppIE1tUCwE3bliwVTpppExz80z8VlkwE43CqUcjk4u0AjFMNSuRvqc/rHoTVu8oFjq7piVk5t8Vrljgg78tlyEudgdkPUqBpaBr+4SNuOzLI9J86BaN8DUJ1lnEQwlk2SxqSjfwtU="
